theme = "harringui"

[editor]
line-number = "relative"
scroll-lines = 1
auto-pairs = true
idle-timeout = 0

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker] 
hidden = true

[editor.lsp]
display-messages = true

# [editor.soft-wrap]
# enable = true
# max-wrap = 25

# [editor.auto-save]
# focus-lost = true

[keys.normal]
g = { a = "code_action" }
"ret" = ["move_line_down", "goto_first_nonwhitespace"] 
X = "extend_line_above"
D = "delete_char_backward"
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
C-g =  [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.insert]
j = { k = "normal_mode" }
