[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
# TODO: gopls needs utf-8 offsets?
indent = { tab-width = 4, unit = "\t" }

[language-server.gopls]
command = "gopls"

[[language]]
name = "zig"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
language-servers = ["marksman", "mdpls"]

[[language]]
name = "go"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[language-server.mdpls]
command = "mdpls"

[language-server.mdpls.config]
markdown.preview.auto = true
markdown.preview.browser = "firefox" 

[[language]]
name = "cpp"
auto-format = false
indent = { tab-width = 4, unit = "    " }

# setup lsp rust
[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

